Add ApkPure in readme
LinwoodCloud/dev_doctor pull request #47
Opened 2021-03-02 20:46 UTC by devilAPI

2021-03-02 20:47 UTC, devilAPI commented
https://apkpure.com/dev-doctor/com.github.linwoodcloud.dev_doctor

2021-03-02 20:58 UTC, devilAPI commented
uploaded by me, straight from github

2021-03-02 21:11 UTC, devilAPI commented
its fine and ready to merge

2021-03-04 06:48 UTC, CodeDoctorDE requested changes

2021-03-04 06:48 UTC, CodeDoctorDE commented on README.md
> +## Community
Okay, I think we don't need this headline any more.

2021-03-04 07:01 UTC, devilAPI commented
did it

2021-03-04 07:03 UTC, CodeDoctorDE commented
I think you removed the wrong section? On this readme, the ios headline belongs to the website links?!

2021-03-04 18:38 UTC, CodeDoctorDE requested changes

2021-03-04 18:38 UTC, CodeDoctorDE commented on README.md
> -### Web
here you see what i mean

2021-03-04 18:38 UTC, CodeDoctorDE commented on README.md
> +### Installation
this was my issue. we don't need an installation section

2021-03-07 09:58 UTC, devilAPI commented
I'm sorry but i have zero clue what you want.

2021-03-07 10:04 UTC, CodeDoctorDE commented
You removed the web headline

2021-03-07 10:06 UTC, CodeDoctorDE commented
![Uploading image.png…]()

2021-03-07 10:06 UTC, CodeDoctorDE commented
![image](https://user-images.githubusercontent.com/20452814/110236277-338ffa00-7f35-11eb-869f-3c28a7f7ed7b.png)

2021-03-07 10:15 UTC, devilAPI commented
fixed

2021-03-07 10:17 UTC, CodeDoctorDE requested changes

2021-03-07 10:17 UTC, CodeDoctorDE commented on README.md
> +Community:
If you add this as a headline, I can approve it! :)
`#### Community`

2021-03-07 11:13 UTC, devilAPI commented
uhh did that

2021-03-07 11:14 UTC, CodeDoctorDE approved these changes
👍

2021-03-07 11:14 UTC, merged